/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#6c63ff',
        secondary: '#232946',
        accent: '#a6a8ff',
        glass: 'rgba(255,255,255,0.7)',
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(108,99,255,0.10)',
      },
      borderRadius: {
        xl: '2rem',
      },
      animation: {
        fade: 'fadeIn 1s ease-in',
        bounceX: 'bounceX 1s infinite',
        gradient: 'gradientBG 8s ease-in-out infinite',
        typewriter: 'typewriter 2.5s steps(20) 1s 1 normal both',
        'spin-slow': 'spin 3s linear infinite',
        'spin-reverse': 'spin 4s linear infinite reverse',
        'spin-slower': 'spin 5s linear infinite',
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'gradient-pulse': 'gradientPulse 3s ease-in-out infinite',
        'gradient-shift': 'gradientShift 4s ease-in-out infinite',
        'gradient-rotate': 'gradientRotate 5s ease-in-out infinite',
        'overlay-fade': 'overlayFade 2s ease-in-out infinite',
        'overlay-shine': 'overlayShine 3s ease-in-out infinite',
        'overlay-sparkle': 'overlaySparkle 4s ease-in-out infinite',
        'float-particle-1': 'floatParticle1 4s ease-in-out infinite',
        'float-particle-2': 'floatParticle2 5s ease-in-out infinite',
        'float-particle-3': 'floatParticle3 6s ease-in-out infinite',
        'float-particle-4': 'floatParticle4 3.5s ease-in-out infinite',
        'float-particle-5': 'floatParticle5 4.5s ease-in-out infinite',
        'float-particle-6': 'floatParticle6 5.5s ease-in-out infinite',
        'float-particle-7': 'floatParticle7 3s ease-in-out infinite',
        'float-particle-8': 'floatParticle8 4.2s ease-in-out infinite',
        'float-particle-9': 'floatParticle9 5.8s ease-in-out infinite',
        'float-particle-10': 'floatParticle10 3.8s ease-in-out infinite',
        'float-particle-11': 'floatParticle11 4.7s ease-in-out infinite',
        'float-particle-12': 'floatParticle12 5.3s ease-in-out infinite',
        'float-particle-13': 'floatParticle13 3.3s ease-in-out infinite',
        'float-particle-14': 'floatParticle14 4.8s ease-in-out infinite',
        'float-particle-15': 'floatParticle15 5.1s ease-in-out infinite',
        'float-particle-16': 'floatParticle16 3.7s ease-in-out infinite',
        'float-particle-17': 'floatParticle17 4.4s ease-in-out infinite',
        'float-particle-18': 'floatParticle18 5.6s ease-in-out infinite',
        'float-particle-19': 'floatParticle19 3.9s ease-in-out infinite',
        'float-particle-20': 'floatParticle20 4.6s ease-in-out infinite',
        'float-particle-21': 'floatParticle21 5.4s ease-in-out infinite',
        'float-particle-22': 'floatParticle22 3.6s ease-in-out infinite',
        'float-particle-23': 'floatParticle23 4.3s ease-in-out infinite',
        'float-particle-24': 'floatParticle24 5.7s ease-in-out infinite',
        'float-particle-25': 'floatParticle25 3.4s ease-in-out infinite',
        'float-particle-26': 'floatParticle26 4.9s ease-in-out infinite',
        'float-particle-27': 'floatParticle27 5.2s ease-in-out infinite',
        'float-particle-28': 'floatParticle28 3.8s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: 0, transform: 'translateY(40px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        bounceX: {
          '0%, 100%': { transform: 'translateX(0)' },
          '50%': { transform: 'translateX(10px)' },
        },
        gradientBG: {
          '0%, 100%': { 'background-position': '0% 50%' },
          '50%': { 'background-position': '100% 50%' },
        },
        typewriter: {
          '0%': { width: '0' },
          '100%': { width: '100%' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 20px rgba(108, 99, 255, 0.3)' },
          '100%': { boxShadow: '0 0 30px rgba(108, 99, 255, 0.6)' },
        },
        gradientPulse: {
          '0%, 100%': { opacity: 0.4, transform: 'scale(1)' },
          '50%': { opacity: 0.6, transform: 'scale(1.05)' },
        },
        gradientShift: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '50%': { transform: 'rotate(180deg)' },
        },
        gradientRotate: {
          '0%': { transform: 'rotate(0deg) scale(1)' },
          '50%': { transform: 'rotate(180deg) scale(1.1)' },
          '100%': { transform: 'rotate(360deg) scale(1)' },
        },
        overlayFade: {
          '0%, 100%': { opacity: 0 },
          '50%': { opacity: 0.2 },
        },
        overlayShine: {
          '0%, 100%': { opacity: 0, transform: 'translateX(-100%)' },
          '50%': { opacity: 0.15, transform: 'translateX(0%)' },
        },
        overlaySparkle: {
          '0%, 100%': { opacity: 0, transform: 'scale(0.8)' },
          '50%': { opacity: 0.1, transform: 'scale(1.2)' },
        },
        floatParticle1: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-8px) translateX(4px)' },
          '50%': { transform: 'translateY(-4px) translateX(-2px)' },
          '75%': { transform: 'translateY(-12px) translateX(6px)' },
        },
        floatParticle2: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '33%': { transform: 'translateY(-6px) translateX(-3px)' },
          '66%': { transform: 'translateY(-10px) translateX(5px)' },
        },
        floatParticle3: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '50%': { transform: 'translateY(-5px) translateX(3px)' },
        },
        floatParticle4: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-7px) translateX(-4px)' },
          '50%': { transform: 'translateY(-3px) translateX(2px)' },
          '75%': { transform: 'translateY(-9px) translateX(-6px)' },
        },
        floatParticle5: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '20%': { transform: 'translateY(-5px) translateX(3px)' },
          '40%': { transform: 'translateY(-8px) translateX(-1px)' },
          '60%': { transform: 'translateY(-2px) translateX(4px)' },
          '80%': { transform: 'translateY(-10px) translateX(-3px)' },
        },
        floatParticle6: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '30%': { transform: 'translateY(-6px) translateX(-2px)' },
          '70%': { transform: 'translateY(-4px) translateX(5px)' },
        },
        floatParticle7: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '50%': { transform: 'translateY(-7px) translateX(-4px)' },
        },
        floatParticle8: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-3px) translateX(6px)' },
          '50%': { transform: 'translateY(-8px) translateX(-1px)' },
          '75%': { transform: 'translateY(-5px) translateX(3px)' },
        },
        floatParticle9: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '33%': { transform: 'translateY(-9px) translateX(2px)' },
          '66%': { transform: 'translateY(-2px) translateX(-5px)' },
        },
        floatParticle10: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '40%': { transform: 'translateY(-6px) translateX(-3px)' },
          '80%': { transform: 'translateY(-4px) translateX(7px)' },
        },
        floatParticle11: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-8px) translateX(1px)' },
          '50%': { transform: 'translateY(-3px) translateX(-4px)' },
          '75%': { transform: 'translateY(-10px) translateX(5px)' },
        },
        floatParticle12: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '30%': { transform: 'translateY(-5px) translateX(6px)' },
          '70%': { transform: 'translateY(-7px) translateX(-2px)' },
        },
        floatParticle13: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '50%': { transform: 'translateY(-6px) translateX(-5px)' },
        },
        floatParticle14: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '20%': { transform: 'translateY(-4px) translateX(3px)' },
          '40%': { transform: 'translateY(-9px) translateX(-1px)' },
          '60%': { transform: 'translateY(-2px) translateX(4px)' },
          '80%': { transform: 'translateY(-8px) translateX(-3px)' },
        },
        floatParticle15: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '33%': { transform: 'translateY(-7px) translateX(-2px)' },
          '66%': { transform: 'translateY(-3px) translateX(5px)' },
        },
        floatParticle16: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-5px) translateX(-4px)' },
          '50%': { transform: 'translateY(-10px) translateX(1px)' },
          '75%': { transform: 'translateY(-4px) translateX(6px)' },
        },
        floatParticle17: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '50%': { transform: 'translateY(-8px) translateX(3px)' },
        },
        floatParticle18: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '30%': { transform: 'translateY(-6px) translateX(-5px)' },
          '70%': { transform: 'translateY(-2px) translateX(4px)' },
        },
        floatParticle19: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-9px) translateX(2px)' },
          '50%': { transform: 'translateY(-4px) translateX(-3px)' },
          '75%': { transform: 'translateY(-7px) translateX(5px)' },
        },
        floatParticle20: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '40%': { transform: 'translateY(-5px) translateX(-6px)' },
          '80%': { transform: 'translateY(-8px) translateX(1px)' },
        },
        floatParticle21: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '33%': { transform: 'translateY(-3px) translateX(4px)' },
          '66%': { transform: 'translateY(-10px) translateX(-2px)' },
        },
        floatParticle22: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '20%': { transform: 'translateY(-7px) translateX(-1px)' },
          '40%': { transform: 'translateY(-2px) translateX(5px)' },
          '60%': { transform: 'translateY(-9px) translateX(3px)' },
          '80%': { transform: 'translateY(-4px) translateX(-4px)' },
        },
        floatParticle23: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '50%': { transform: 'translateY(-6px) translateX(-3px)' },
        },
        floatParticle24: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-8px) translateX(4px)' },
          '50%': { transform: 'translateY(-3px) translateX(-2px)' },
          '75%': { transform: 'translateY(-10px) translateX(6px)' },
        },
        floatParticle25: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '30%': { transform: 'translateY(-5px) translateX(-5px)' },
          '70%': { transform: 'translateY(-7px) translateX(2px)' },
        },
        floatParticle26: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '40%': { transform: 'translateY(-4px) translateX(3px)' },
          '80%': { transform: 'translateY(-9px) translateX(-1px)' },
        },
        floatParticle27: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '33%': { transform: 'translateY(-6px) translateX(-4px)' },
          '66%': { transform: 'translateY(-2px) translateX(5px)' },
        },
        floatParticle28: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-7px) translateX(1px)' },
          '50%': { transform: 'translateY(-5px) translateX(-3px)' },
          '75%': { transform: 'translateY(-8px) translateX(4px)' },
        },
      },
    },
  },
  darkMode: 'class',
  plugins: [],
};

